// <auto-generated />
using MerkezKur.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace MerkezKur.DataAccess.Migrations
{
    [DbContext(typeof(MerkezKurDbContext))]
    partial class MerkezKurDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.7")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("MerkezKur.Entities.Kurlar", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<double>("BanknoteBuying")
                        .HasColumnType("double precision");

                    b.Property<double>("BanknoteSelling")
                        .HasColumnType("double precision");

                    b.Property<string>("Code")
                        .HasColumnType("text");

                    b.Property<string>("CrossRateName")
                        .HasColumnType("text");

                    b.Property<string>("DatetimeKurGet")
                        .HasColumnType("text");

                    b.Property<double>("ForexBuying")
                        .HasColumnType("double precision");

                    b.Property<double>("ForexSelling")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("Kurlars");
                });
#pragma warning restore 612, 618
        }
    }
}
